=== claudiobogossian/terralib5/schemas/terralib/qt/af/usettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:te_qt_af="http://www.terralib.org/schemas/qt/af"
            xmlns:te_common="http://www.terralib.org/schemas/common"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.terralib.org/schemas/qt/af"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            xml:lang="en">

  <xsd:annotation>
    <xsd:appinfo>User settings file</xsd:appinfo>
    <xsd:documentation>A simple schema for the application's user settings</xsd:documentation>
  </xsd:annotation>

  <xsd:import namespace="http://www.terralib.org/schemas/common" schemaLocation="../../common/common.xsd"/>
  <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../../ogc/xlink/1.0.0/xlinks.xsd"/>

  <xsd:element name="UserSettings" type="te_qt_af:UserSettingsType" />

  <xsd:complexType name="UserSettingsType">
    <xsd:annotation>
      <xsd:documentation>A type used to describe configurations</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="SelectedIconTheme" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="LastSearchedFolder" type="te_common:OnlineResourceType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="ToolBarIconSize" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="DefaultSRID" type="xsd:integer" minOccurs="0" maxOccurs="1" default="0"/>
	  <xsd:element name="SelectionColor" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="SpecificPlugins" type="te_qt_af:SpecificPluginsType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="EnabledPlugins" type="te_qt_af:EnabledPluginsType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="DataSourcesFileName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="MostRecentProject" type="te_common:OnlineResourceType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="RecentProjects" type="te_qt_af:RecentProjectsType" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required" />
  </xsd:complexType>

  <xsd:complexType name="SpecificPluginsType">
    <xsd:sequence>
      <xsd:element name="Plugin" type="te_qt_af:SpecificPluginType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="SpecificPluginType">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1" />
      <xsd:element name="Path" type="te_common:OnlineResourceType" minOccurs="1" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="EnabledPluginsType">
    <xsd:sequence>
      <xsd:element name="Plugin" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="RecentProjectsType">
    <xsd:sequence>
      <xsd:element name="Project" type="te_qt_af:RecentProjectType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="RecentProjectType">
    <xsd:attributeGroup ref="xlink:simpleLink"/>
    <xsd:attribute name="title" type="xsd:string" use="required" />
  </xsd:complexType>

</xsd:schema>

=== claudiobogossian/terralib5/schemas/terralib/qt/af/user_settings.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<UserSettings xmlns:te_qt_af="http://www.terralib.org/schemas/qt/af"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.terralib.org/schemas/qt/af"
         xsd:schemaLocation="http://www.terralib.org/schemas/qt/af usettings.xsd"
         version="5.0.0">
  <SelectedIconTheme>tango</SelectedIconTheme>

  <LastSearchedFolder xlink:href="C:/Users/gribeiro/Documents"/>

  <ToolBarIconSize>24</ToolBarIconSize>
  
  <DefaultSRID>4326</DefaultSRID>
  
  <SelectionColor>#00FF00</SelectionColor>

  <SpecificPlugins>
    <Plugin>
      <Name>te.da.gdal</Name>
      <Path xlink:href="plugins\gdal\plugin_info.xml" />
    </Plugin>
    <Plugin>
      <Name>te.plugin.exchanger</Name>
      <Path xlink:href="plugins\plugin_exchanger\plugin_info.xml" />
    </Plugin>
    <Plugin>
      <Name>te.cellspace.builder</Name>
      <Path xlink:href="plugins\plugin_cellspace_builder\plugin_info.xml" />
    </Plugin>
  </SpecificPlugins>

  <EnabledPlugins>
    <Plugin>te.da.ogr</Plugin>
    <Plugin>te.da.gdal</Plugin>
    <Plugin>te.da.pgis</Plugin>
    <Plugin>te.plugin.builder</Plugin>
  </EnabledPlugins>

  <DataSourcesFileName>datasources.xml</DataSourcesFileName>

  <MostRecentProject xlink:href="../../conf/project.xml"/>

  <RecentProjects>
    <Project xlink:href="../../conf/brasil.xml" title="Atlas Brasil"/>
    <Project xlink:href="../../conf/project.xml" title="Estudo Agricola do Estado de Minas Gerais"/>
    <Project xlink:href="../../conf/super-project.xml" title="Super projeto"/>
  </RecentProjects>
</UserSettings>
