=== claudiobogossian/terralib5/share/terralib/schemas/terralib/qt/af/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:te_qt_af="http://www.terralib.org/schemas/qt/af"
            xmlns:te_common="http://www.terralib.org/schemas/common"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.terralib.org/schemas/qt/af"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            xml:lang="en">

  <xsd:annotation>
    <xsd:appinfo>Framework Configuration Schema</xsd:appinfo>
    <xsd:documentation>A simple schema for the framework configuration</xsd:documentation>
  </xsd:annotation>

  <xsd:import namespace="http://www.terralib.org/schemas/common" schemaLocation="../../common/common.xsd"/>
  <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../../ogc/xlink/1.0.0/xlinks.xsd"/>

  <xsd:element name="Application" type="te_qt_af:ApplicationType" />

  <xsd:complexType name="ApplicationType">
    <xsd:annotation>
      <xsd:documentation>A type used to describe configurations</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="Organization" type="xsd:string" minOccurs="1" maxOccurs="1" />
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1" />
      <xsd:element name="Title" type="xsd:string" minOccurs="1" maxOccurs="1" />
	  <xsd:element name="ProjectExtension" type="xsd:string" minOccurs="1" maxOccurs="1" />
      <xsd:element name="IconName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="UserSettingsFileName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="PluginsFileName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="HelpFile" type="te_common:OnlineResourceType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="DataSourcesFileName" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="IconThemeInfo" type="te_qt_af:IconThemeInfoType" minOccurs="1" maxOccurs="1" />
      <xsd:element name="ToolBarDefaultIconSize" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="DefaultSRID" type="xsd:integer" minOccurs="0" maxOccurs="1" default="0"/>
	  <xsd:element name="DefaultSelectionColor" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="IconThemeInfoType">
    <xsd:sequence>
      <xsd:element name="BaseDirectory" type="te_common:OnlineResourceType" minOccurs="1" maxOccurs="1" />
      <xsd:element name="DefaultTheme" type="xsd:string" minOccurs="1" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== claudiobogossian/terralib5/share/terralib/schemas/terralib/qt/af/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Application xmlns:te_qt_af="http://www.terralib.org/schemas/qt/af"
             xmlns:xlink="http://www.w3.org/1999/xlink"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.terralib.org/schemas/qt/af"
             xsd:schemaLocation="http://www.terralib.org/schemas/qt/af config.xsd"
             version="5.0.0">
  <Organization>INPE</Organization>
  <Name>TerraView</Name>
  <Title>TerraView</Title>
  <ProjectExtension>tview</ProjectExtension>
  <IconName>terraview</IconName>
  <UserSettingsFileName>user_settings.xml</UserSettingsFileName>
  <PluginsFileName>application_plugins.xml</PluginsFileName>
  <HelpFile xlink:href="terraview.qhc"/>
  <DataSourcesFileName>datasources.xml</DataSourcesFileName>
  <IconThemeInfo>
    <BaseDirectory xlink:href="../../icons"/>
    <DefaultTheme>tango</DefaultTheme>
  </IconThemeInfo>
  <ToolBarDefaultIconSize>24</ToolBarDefaultIconSize>
  <DefaultSRID>4326</DefaultSRID>
  <DefaultSelectionColor>#00FF00</DefaultSelectionColor>
</Application>

=== claudiobogossian/terralib5/share/terraview/config/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Application xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.terralib.org/schemas/af"
             xsd:schemaLocation="http://www.terralib.org/schemas/af ../../terralib/schemas/terralib/qt/af/config.xsd"
             version="5.0.0"
             release="2011-01-01">
  <Organization>INPE</Organization>
  <Name>TerraView</Name>
  <Title>TerraView</Title>
  <ProjectExtension>tview</ProjectExtension>
  <IconName>share/terraview/images/png/terralib-globe-small.png</IconName>
  <HelpFile xlink:href="share/terraview/help/help.qhc"/>
  <Plugins xlink:href="share/terralib/plugins/terraview_plugins.json"/>
  <IconThemeInfo>
    <BaseDirectory xlink:href="share/terralib/icons"/>
    <DefaultTheme>terralib</DefaultTheme>
  </IconThemeInfo>
  <ToolBarDefaultIconSize>24</ToolBarDefaultIconSize>
  <DefaultSRID>0</DefaultSRID>
  <DefaultSelectionColor>#00FF00</DefaultSelectionColor>
  <AboutDialogLogo xlink:href="share/terraview/images/png/terraview-textual.png"/>
  <TerraLibLogo xlink:href="share/terralib/images/png/terralib-globe.png"/>
</Application>
