=== claudiobogossian/terralib5/schemas/terralib/dataaccess/query_dialect.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:te_common="http://www.terralib.org/common"
            xmlns:te_da="http://www.terralib.org/dataaccess"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.terralib.org/dataaccess"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            xml:lang="en">

  <xsd:annotation>
    <xsd:appinfo>QueryDialect</xsd:appinfo>
    <xsd:documentation>This XML Schema describes the query dialects provided by Data Access drivers</xsd:documentation>
  </xsd:annotation>

  <xsd:import namespace="http://www.terralib.org/common" schemaLocation="../common/common.xsd"/>
  <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../ogc/xlink/1.0.0/xlinks.xsd"/>

  <xsd:element name="QueryDialect" type="te_da:QueryDialectType">
    <xsd:annotation>
      <xsd:documentation>This is the root element for query dialects files.</xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <xsd:complexType name="QueryDialectType">
    <xsd:annotation>
      <xsd:documentation>This type describes a query dialect.</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="DriverName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Functions" type="te_da:FunctionsType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="FunctionsType">
    <xsd:sequence>
      <xsd:element name="Function" type="te_da:FunctionType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>

  <xsd:element name="SQLFunctionEncoder" type="te_da:SQLFunctionEncoderType" abstract="true"/>

  <xsd:complexType name="SQLFunctionEncoderType" abstract="true"/>

  <xsd:element name="BinaryOpEncoder" type="te_da:BinaryOpEncoderType" substitutionGroup="te_da:SQLFunctionEncoder"/>

  <xsd:element name="UnaryOpEncoder" type="te_da:UnaryOpEncoderType" substitutionGroup="te_da:SQLFunctionEncoder"/>

  <xsd:element name="FunctionEncoder" type="te_da:FunctionEncoderType" substitutionGroup="te_da:SQLFunctionEncoder"/>

  <xsd:element name="TemplateEncoder" type="te_da:TemplateEncoderType" substitutionGroup="te_da:SQLFunctionEncoder"/>

  <xsd:complexType name="FunctionType">
    <xsd:sequence>
      <xsd:element ref="te_da:SQLFunctionEncoder" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BinaryOpEncoderType">
    <xsd:complexContent>
      <xsd:extension base="te_da:SQLFunctionEncoderType">
        <xsd:attribute name="alias" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="UnaryOpEncoderType">
    <xsd:complexContent>
      <xsd:extension base="te_da:SQLFunctionEncoderType">
        <xsd:attribute name="alias" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="FunctionEncoderType">
    <xsd:complexContent>
      <xsd:extension base="te_da:SQLFunctionEncoderType">
        <xsd:attribute name="alias" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="TemplateEncoderType">
    <xsd:complexContent>
      <xsd:extension base="te_da:SQLFunctionEncoderType">
        <xsd:attribute name="alias" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

</xsd:schema>

=== claudiobogossian/terralib5/schemas/terralib/dataaccess/query_dialect.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QueryDialect xmlns:xlink="http://www.w3.org/1999/xlink"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.terralib.org/dataaccess"
              xsd:schemaLocation="http://www.terralib.org/dataaccess query_dialect.xsd"
              version="5.0.0-20110110">
  <DriverName>te.da.sqlite</DriverName>

  <Functions>
    <!-- arithmetic operators -->
    
    <Function name="+">
      <BinaryOpEncoder alias="+"/>
    </Function>

    <Function name="-">
      <BinaryOpEncoder alias="-"/>
    </Function>

    <Function name="*">
      <BinaryOpEncoder alias="*"/>
    </Function>

    <Function name="/">
      <BinaryOpEncoder alias="/"/>
    </Function>
    
    <!-- relational operators -->

    <Function name="=">
      <BinaryOpEncoder alias="="/>
    </Function>

    <Function name="&#60;&#62;">
      <BinaryOpEncoder alias="&#60;&#62;"/>
    </Function>

    <Function name="&#62;">
      <BinaryOpEncoder alias="&#62;"/>
    </Function>

    <Function name="&#60;">
      <BinaryOpEncoder alias="&#60;"/>
    </Function>

    <Function name="&#62;=">
      <BinaryOpEncoder alias="&#62;="/>
    </Function>
    
    <Function name="&#60;=">
      <BinaryOpEncoder alias="&#60;="/>
    </Function>

    <!-- logical operators -->
    
    <Function name="and">
      <BinaryOpEncoder alias="AND"/>
    </Function>
    
    <Function name="or">
      <BinaryOpEncoder alias="OR"/>
    </Function>
    
    <Function name="not">
      <UnaryOpEncoder alias="NOT"/>
    </Function>

    <!-- string operators -->
    
    <Function name="upper">
      <FunctionEncoder alias="upper"/>
    </Function>

    <Function name="lower">
      <FunctionEncoder alias="lower"/>
    </Function>
    
    <Function name="substr">
      <FunctionEncoder alias="substr"/>
    </Function>
    
    <Function name="trim">
      <FunctionEncoder alias="trim"/>
    </Function>
    
    <!-- aggregate operators -->

    <Function name="sum">
      <FunctionEncoder alias="SUM"/>
    </Function>

    <Function name="avg">
      <FunctionEncoder alias="AVG"/>
    </Function>
    
    <Function name="count">
      <FunctionEncoder alias="COUNT"/>
    </Function>
    
    <Function name="max">
      <FunctionEncoder alias="MAX"/>
    </Function>
    
    <Function name="min">
      <FunctionEncoder alias="MIN"/>
    </Function>

    <!-- spatial operators -->
    
    <Function name="st_astext">
      <FunctionEncoder alias="ST_AsText"/>
    </Function>

    <Function name="st_asbinary">
      <FunctionEncoder alias="ST_AsBinary"/>
    </Function>

    <Function name="st_assvg">
      <FunctionEncoder alias="AsSVG"/>
    </Function>

    <Function name="st_askml">
      <FunctionEncoder alias="AsKml"/>
    </Function>

    <Function name="st_asgml">
      <FunctionEncoder alias="AsGml"/>
    </Function>

    <Function name="st_dimension">
      <FunctionEncoder alias="ST_Dimension"/>
    </Function>

    <Function name="st_coorddim">
      <FunctionEncoder alias="CoordDimension"/>
    </Function>

    <Function name="st_geometrytype">
      <FunctionEncoder alias="ST_GeometryType"/>
    </Function>

    <Function name="st_srid">
      <FunctionEncoder alias="ST_SRID"/>
    </Function>

    <Function name="st_setsrid">
      <FunctionEncoder alias="SetSRID"/>
    </Function>

    <Function name="st_isempty">
      <FunctionEncoder alias="ST_IsEmpty"/>
    </Function>

    <Function name="st_issimple">
      <FunctionEncoder alias="ST_IsSimple"/>
    </Function>

    <Function name="st_valid">
      <FunctionEncoder alias="ST_IsValid"/>
    </Function>

    <Function name="st_boundary">
      <FunctionEncoder alias="ST_Boundary"/>
    </Function>

    <Function name="st_envelope">
      <FunctionEncoder alias="ST_Envelope"/>
    </Function>

    <Function name="st_x">
      <FunctionEncoder alias="ST_X"/>
    </Function>

    <Function name="st_y">
      <FunctionEncoder alias="ST_Y"/>
    </Function>

    <Function name="st_z">
      <FunctionEncoder alias="ST_Z"/>
    </Function>
    
    <Function name="st_m">
      <FunctionEncoder alias="ST_M"/>
    </Function>
    
    <Function name="st_startpoint">
      <FunctionEncoder alias="ST_StartPoint"/>
    </Function>
    
    <Function name="st_endpoint">
      <FunctionEncoder alias="ST_EndPoint"/>
    </Function>
    
    <Function name="st_length">
      <FunctionEncoder alias="ST_Length"/>
    </Function>
    
    <Function name="geodesiclength">
      <FunctionEncoder alias="GeodesicLength"/>
    </Function>
    
    <Function name="st_greatcirclelength">
      <FunctionEncoder alias="GreatCircleLength"/>
    </Function>

    <Function name="st_isclosed">
      <FunctionEncoder alias="ST_IsClosed"/>
    </Function>

    <Function name="st_isring">
      <FunctionEncoder alias="ST_IsRing"/>
    </Function>

    <Function name="st_pointonsurface">
      <FunctionEncoder alias="ST_PointOnSurface"/>
    </Function>

    <Function name="st_numpoints">
      <FunctionEncoder alias="ST_NumPoints"/>
    </Function>

    <Function name="st_pointn">
      <FunctionEncoder alias="ST_PointN"/>
    </Function>

    <Function name="st_centroid">
      <FunctionEncoder alias="ST_Centroid"/>
    </Function>

    <Function name="st_area">
      <FunctionEncoder alias="ST_Area"/>
    </Function>

    <Function name="st_exteriorring">
      <FunctionEncoder alias="ST_ExteriorRing"/>
    </Function>

    <Function name="st_numinteriorrings">
      <FunctionEncoder alias="ST_NumInteriorRings"/>
    </Function>

    <Function name="st_interiorringn">
      <FunctionEncoder alias="ST_InteriorRingN"/>
    </Function>

    <Function name="st_numgeometries">
      <FunctionEncoder alias="ST_NumGeometries"/>
    </Function>

    <Function name="st_geometryn">
      <FunctionEncoder alias="ST_GeometryN"/>
    </Function>

    <Function name="st_equals">
      <FunctionEncoder alias="ST_Equals"/>
    </Function>

    <Function name="st_disjoint">
      <FunctionEncoder alias="ST_Disjoint"/>
    </Function>

    <Function name="st_touches">
      <FunctionEncoder alias="ST_Touches"/>
    </Function>

    <Function name="st_within">
      <FunctionEncoder alias="ST_Within"/>
    </Function>
    
    <Function name="st_overlaps">
      <FunctionEncoder alias="ST_Overlaps"/>
    </Function>
    
    <Function name="st_crosses">
      <FunctionEncoder alias="ST_Crosses"/>
    </Function>

    <Function name="st_intersects">
      <FunctionEncoder alias="ST_Intersects"/>
    </Function>

    <Function name="st_contains">
      <FunctionEncoder alias="ST_Contains"/>
    </Function>

    <Function name="st_covers">
      <FunctionEncoder alias="ST_Covers"/>
    </Function>

    <Function name="st_coveredby">
      <FunctionEncoder alias="ST_CoveredBy"/>
    </Function>

    <Function name="st_relate">
      <FunctionEncoder alias="ST_Relate"/>
    </Function>

    <Function name="st_distance">
      <FunctionEncoder alias="ST_Distance"/>
    </Function>

    <Function name="ptdistwithin">
      <FunctionEncoder alias="PtDistWithin"/>
    </Function>

    <Function name="st_intersection">
      <FunctionEncoder alias="ST_Intersection"/>
    </Function>

    <Function name="st_difference">
      <FunctionEncoder alias="ST_Difference"/>
    </Function>

    <Function name="st_union">
      <FunctionEncoder alias="ST_Union"/>
    </Function>

    <Function name="st_symdifference">
      <FunctionEncoder alias="ST_SymDifference"/>
    </Function>

    <Function name="st_buffer">
      <FunctionEncoder alias="ST_Buffer"/>
    </Function>

    <Function name="st_convexhull">
      <FunctionEncoder alias="ST_ConvexHull"/>
    </Function>

    <Function name="offsetcurve">
      <FunctionEncoder alias="OgffsetCurve"/>
    </Function>

    <Function name="commonedges">
      <FunctionEncoder alias="CommonEdges"/>
    </Function>

    <!-- MBR operators -->

    <Function name="mbrequal">
      <FunctionEncoder alias="MbrEqual"/>
    </Function>

    <Function name="mbrdisjoint">
      <FunctionEncoder alias="MbrDisjoint"/>
    </Function>

    <Function name="mbrtouches">
      <FunctionEncoder alias="MbrTouches"/>
    </Function>

    <Function name="mbrwithin">
      <FunctionEncoder alias="MbrWithin"/>
    </Function>

    <Function name="mbroverlaps">
      <FunctionEncoder alias="MbrOverlaps"/>
    </Function>

    <Function name="mbrcontains">
      <FunctionEncoder alias="MbrContains"/>
    </Function>

    <!-- SRS operators -->

    <Function name="st_transform">
      <FunctionEncoder alias="Transform"/>
    </Function>

  </Functions>
</QueryDialect>

=== claudiobogossian/terralib5/resources/xml/sqlite-nonspatial-dialect.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QueryDialect xmlns:xlink="http://www.w3.org/1999/xlink"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.terralib.org/dataaccess"
              xsd:schemaLocation="http://www.terralib.org/dataaccess ../../../../schemas/terralib/dataaccess/query_dialect.xsd"
              version="5.0.0-20110110">
  <DriverName>te.da.sqlite</DriverName>
  
  <Functions>
    <!-- arithmetic operators -->
    
    <Function name="+">
      <BinaryOpEncoder alias="+"/>
    </Function>
	
    <Function name="-">
      <BinaryOpEncoder alias="-"/>
    </Function>
	
    <Function name="*">
      <BinaryOpEncoder alias="*"/>
    </Function>
	
    <Function name="/">
      <BinaryOpEncoder alias="/"/>
    </Function>
    
    <!-- relational operators -->
	
    <Function name="=">
      <BinaryOpEncoder alias="="/>
    </Function>
	
    <Function name="&#60;&#62;">
      <BinaryOpEncoder alias="&#60;&#62;"/>
    </Function>
	
    <Function name="&#62;">
      <BinaryOpEncoder alias="&#62;"/>
    </Function>
	
    <Function name="&#60;">
      <BinaryOpEncoder alias="&#60;"/>
    </Function>
	
    <Function name="&#62;=">
      <BinaryOpEncoder alias="&#62;="/>
    </Function>
    
    <Function name="&#60;=">
      <BinaryOpEncoder alias="&#60;="/>
    </Function>
	
    <!-- logical operators -->
    
    <Function name="and">
      <BinaryOpEncoder alias="AND"/>
    </Function>
    
    <Function name="or">
      <BinaryOpEncoder alias="OR"/>
    </Function>
    
    <Function name="not">
      <UnaryOpEncoder alias="NOT"/>
    </Function>
	
    <!-- string operators -->
    
    <Function name="upper">
      <FunctionEncoder alias="upper"/>
    </Function>
	
    <Function name="lower">
      <FunctionEncoder alias="lower"/>
    </Function>
    
    <Function name="substr">
      <FunctionEncoder alias="substr"/>
    </Function>
    
    <Function name="trim">
      <FunctionEncoder alias="trim"/>
    </Function>
    
    <!-- aggregate operators -->
	
    <Function name="sum">
      <FunctionEncoder alias="SUM"/>
    </Function>
	
    <Function name="avg">
      <FunctionEncoder alias="AVG"/>
    </Function>
    
    <Function name="count">
      <FunctionEncoder alias="COUNT"/>
    </Function>
    
    <Function name="max">
      <FunctionEncoder alias="MAX"/>
    </Function>
    
    <Function name="min">
      <FunctionEncoder alias="MIN"/>
    </Function>
 
  </Functions>
</QueryDialect>

=== claudiobogossian/terralib5/resources/xml/mysql-dialect.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QueryDialect xmlns:xlink="http://www.w3.org/1999/xlink"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.terralib.org/schemas/dataaccess"
              xsd:schemaLocation="http://www.terralib.org/schemas/dataaccess ../../../../schemas/terralib/dataaccess/query_dialect.xsd"
              version="5.0.0-20110110">
  <DriverName>te.da.mysql</DriverName>
  
  <Functions>
    <!-- arithmetic operators -->
    
    <Function name="+">
      <BinaryOpEncoder alias="+"/>
    </Function>
	
    <Function name="-">
      <BinaryOpEncoder alias="-"/>
    </Function>
	
    <Function name="*">
      <BinaryOpEncoder alias="*"/>
    </Function>
	
    <Function name="/">
      <BinaryOpEncoder alias="/"/>
    </Function>
    
    <!-- relational operators -->
	
    <Function name="=">
      <BinaryOpEncoder alias="="/>
    </Function>
	
    <Function name="&#60;&#62;">
      <BinaryOpEncoder alias="&#60;&#62;"/>
    </Function>
	
    <Function name="&#62;">
      <BinaryOpEncoder alias="&#62;"/>
    </Function>
	
    <Function name="&#60;">
      <BinaryOpEncoder alias="&#60;"/>
    </Function>
	
    <Function name="&#62;=">
      <BinaryOpEncoder alias="&#62;="/>
    </Function>
    
    <Function name="&#60;=">
      <BinaryOpEncoder alias="&#60;="/>
    </Function>
	
    <!-- logical operators -->
    
    <Function name="and">
      <BinaryOpEncoder alias="AND"/>
    </Function>
    
    <Function name="or">
      <BinaryOpEncoder alias="OR"/>
    </Function>
    
    <Function name="not">
      <UnaryOpEncoder alias="NOT"/>
    </Function>
	
    <!-- string operators -->
    
    <Function name="upper">
      <FunctionEncoder alias="upper"/>
    </Function>
	
    <Function name="lower">
      <FunctionEncoder alias="lower"/>
    </Function>
    
    <Function name="substr">
      <FunctionEncoder alias="substr"/>
    </Function>
    
    <Function name="trim">
      <FunctionEncoder alias="trim"/>
    </Function>
    
    <!-- aggregate operators -->
	
    <Function name="sum">
      <FunctionEncoder alias="SUM"/>
    </Function>
	
    <Function name="avg">
      <FunctionEncoder alias="AVG"/>
    </Function>
    
    <Function name="count">
      <FunctionEncoder alias="COUNT"/>
    </Function>
    
    <Function name="max">
      <FunctionEncoder alias="MAX"/>
    </Function>
    
    <Function name="min">
      <FunctionEncoder alias="MIN"/>
    </Function>
	
    <!-- spatial operators -->
    
    <Function name="st_astext">
      <FunctionEncoder alias="AsText"/>
    </Function>
    
    <Function name="st_asbinary">
      <FunctionEncoder alias="AsBinary"/>
    </Function>
   
    <Function name="st_dimension">
      <FunctionEncoder alias="Dimension"/>
    </Function>
    
    <Function name="st_envelope">
      <FunctionEncoder alias="Envelope"/>
    </Function>
    
    <Function name="st_geometrytype">
      <FunctionEncoder alias="GeometryType"/>
    </Function>
    
    <Function name="st_srid">
      <FunctionEncoder alias="SRID"/>
    </Function>
    
    <Function name="st_boundary">
      <FunctionEncoder alias="Boundary"/>
    </Function>
    
    <Function name="st_isempty">
      <FunctionEncoder alias="IsEmpty"/>
    </Function>
    
    <Function name="st_issimple">
      <FunctionEncoder alias="IsSimple"/>
    </Function>
	
    <Function name="st_isring">
      <FunctionEncoder alias="IsRing"/>
    </Function>
    
    <Function name="st_x">
      <FunctionEncoder alias="X"/>
    </Function>
    
    <Function name="st_y">
      <FunctionEncoder alias="Y"/>
    </Function>
    
    <Function name="st_endpoint">
      <FunctionEncoder alias="EndPoint"/>
    </Function>
    
    <Function name="st_length">
      <FunctionEncoder alias="GLength"/>
    </Function>
    
    <Function name="st_numpoints">
      <FunctionEncoder alias="NumPoints"/>
    </Function>
    
    <Function name="st_pointn">
      <FunctionEncoder alias="PointN"/>
    </Function>
    
    <Function name="st_startpoint">
      <FunctionEncoder alias="StartPoint"/>
    </Function>
    
    <Function name="st_isclosed">
      <FunctionEncoder alias="IsClosed"/>
    </Function>
    
    <Function name="st_area">
      <FunctionEncoder alias="Area"/>
    </Function>
    
    <Function name="st_exteriorring">
      <FunctionEncoder alias="ExteriorRing"/>
    </Function>
	
	<Function name="st_centroid">
      <FunctionEncoder alias="Centroid"/>
    </Function>
    
    <Function name="st_interiorringn">
      <FunctionEncoder alias="InteriorRingN"/>
    </Function>
    
    <Function name="st_numinteriorrings">
      <FunctionEncoder alias="NumInteriorRings"/>
    </Function>
    
    <Function name="st_geometryn">
      <FunctionEncoder alias="GeometryN"/>
    </Function>
    
    <Function name="st_numgeometries">
      <FunctionEncoder alias="NumGeometries"/>
    </Function>
    
    <Function name="st_buffer">
      <FunctionEncoder alias="Buffer"/>
    </Function>
    
    <Function name="st_convexhull">
      <FunctionEncoder alias="ConvexHull"/>
    </Function>
    
    <Function name="st_difference">
      <FunctionEncoder alias="Difference"/>
    </Function>
    
    <Function name="st_intersection">
      <FunctionEncoder alias="Intersection"/>
    </Function>
    
    <Function name="st_symdifference">
      <FunctionEncoder alias="SymDifference"/>
    </Function>
    
    <Function name="st_union">
      <FunctionEncoder alias="Union"/>
    </Function>
    
    <Function name="st_contains">
      <FunctionEncoder alias="Contains"/>
    </Function>
    
    <Function name="st_crosses">
      <FunctionEncoder alias="Crosses"/>
    </Function>
    
    <Function name="st_disjoint">
      <FunctionEncoder alias="Disjoint"/>
    </Function>
    
    <Function name="st_equals">
      <FunctionEncoder alias="Equals"/>
    </Function>
    
    <Function name="st_intersects">
      <FunctionEncoder alias="Intersects"/>
    </Function>
    
    <Function name="st_overlaps">
      <FunctionEncoder alias="Overlaps"/>
    </Function>
    
    <Function name="st_touches">
      <FunctionEncoder alias="Touches"/>
    </Function>
    
    <Function name="st_within">
      <FunctionEncoder alias="Within"/>
    </Function>

  </Functions>
</QueryDialect>
