=== claudiobogossian/terralib5/schemas/terralib/plugin/plugin_info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:plugin="http://www.terralib.org/schemas/plugin"
            xmlns:common="http://www.terralib.org/schemas/common"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.terralib.org/schemas/plugin"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            xml:lang="en">

  <xsd:annotation>
    <xsd:appinfo>PluginInfo</xsd:appinfo>
    <xsd:documentation>This XML Schema describes the information about a given Terralib Plugin</xsd:documentation>
  </xsd:annotation>

  <xsd:import namespace="http://www.terralib.org/schemas/common" schemaLocation="../common/common.xsd"/>
  <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../ogc/xlink/1.0.0/xlinks.xsd"/>

  <xsd:element name="PluginInfo" type="plugin:PluginInfoType">
    <xsd:annotation>
      <xsd:documentation>This is the root element for plugin configuration files.</xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <xsd:complexType name="PluginInfoType">
    <xsd:annotation>
      <xsd:documentation>This type describes the plugin type.</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="DisplayName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Description" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="TerraLibVersion" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="License" type="plugin:LicenseType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Category" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Site" type="common:OnlineResourceType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Provider" type="plugin:ProviderType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="RequiredPlugins" type="plugin:RequiredPluginsType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="RequiredPluginCategory" type="plugin:RequiredPluginCategoryType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="RequiredModules" type="plugin:RequiredModulesType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Resources" type="plugin:ResourcesType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Parameters" type="plugin:ParametersType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
    <xsd:attribute name="release" type="xsd:date" use="required"/>
    <xsd:attribute name="engine" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="LicenseType">
    <xsd:annotation>
      <xsd:documentation>You can include a reference to an on-line resource from where the license can be accessed.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attributeGroup ref="xlink:simpleLink"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:complexType name="ProviderType">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Site" type="common:OnlineResourceType" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Email" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>  
  </xsd:complexType>

  <xsd:complexType name="RequiredPluginsType">
    <xsd:sequence>
      <xsd:element name="PluginId" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
  
  <xsd:complexType name="RequiredPluginCategoryType">
    <xsd:sequence>
      <xsd:element name="CategoryId" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
  
  <xsd:complexType name="RequiredModulesType">
    <xsd:sequence>
      <xsd:element name="ModuleId" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>

  <xsd:complexType name="ResourcesType">
    <xsd:sequence>
      <xsd:element name="Resource" type="plugin:ResourceType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>

  <xsd:complexType name="ResourceType">
    <xsd:annotation>
      <xsd:documentation>If your plugin need to track any resource you can use a resource to point to it.</xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attributeGroup ref="xlink:simpleLink"/>
  </xsd:complexType>

  <xsd:complexType name="ParametersType">
    <xsd:sequence>
      <xsd:element name="Parameter" type="plugin:ParameterType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>

  <xsd:complexType name="ParameterType">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Value" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>  
  </xsd:complexType>

</xsd:schema>

=== claudiobogossian/terralib5/src/terralib/binding/v8/plugin/plugin_info.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PluginInfo xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.terralib.org/schemas/plugin"
        xsd:schemaLocation="http://www.terralib.org/schemas/plugin ../../../../myschemas/terralib/plugin/plugin_info.xsd"
        version="5.0.0-20110110"
        release="2011-01-01"
        engine="C++">
  <Name>te.js.plugin</Name>
  <DisplayName>.......</DisplayName>
  <Description>This plugin enables TerraLib to ...</Description>
  <TerraLibVersion>5.0.0-20100101</TerraLibVersion>
  <License xlink:href="http://www.gnu.org/licenses/lgpl-3.0-standalone.html">GNU Lesser General Public License v 3.0</License>
  <Category>Bindings</Category>
  <Site xlink:href="http://www.dpi.inpe.br/terralib5/wiki/doku.php?id=wiki:designimplementation:dataaccess:postgis"></Site>
  <Provider>
    <Name>Terralib Team</Name>
    <Site xlink:href="http://www.terralib.org/"></Site>
    <Email>terralib-team@terralib.org</Email>
  </Provider>
  <Resources>
    <Resource name="SharedLibraryName" xlink:href="terralib_binding_v8_plugin"></Resource>
  </Resources>
</PluginInfo>

=== claudiobogossian/terralib5/schemas/terralib/plugin/plugin_info.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PluginInfo xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.terralib.org/schemas/plugin"
            xsd:schemaLocation="http://www.terralib.org/schemas/plugin plugin_info.xsd"
            version="5.0.0-20110110"
            release="2011-01-01"
            engine="C++">
  <Name>te.da.pgis</Name>
  <DisplayName>PostGIS Data Source Driver</DisplayName>
  <Description>This plugin enables TerraLib to access data in a PostgreSQL DBMS using the PostGIS extension</Description>
  <TerraLibVersion>5.0.0-20100101</TerraLibVersion>
  <License xlink:href="http://www.gnu.org/licenses/lgpl-3.0-standalone.html">GNU Lesser General Public License v 3.0</License>
  <Category>Data Access</Category>
  <Site xlink:href="http://www.dpi.inpe.br/terralib5/wiki/doku.php?id=wiki:designimplementation:dataaccess:postgis"/>
  <Provider>
    <Name>Terralib Team</Name>
    <Site xlink:href="http://www.terralib.org/"/>
    <Email>terralib-team@terralib.org</Email>
  </Provider>
  <RequiredPlugins>
    <PluginId>te.plugin</PluginId>
  </RequiredPlugins>
  <RequiredModules>
    <ModuleId>te.common</ModuleId>
  <ModuleId>te.dt</ModuleId>
    <ModuleId>te.da</ModuleId>
  <ModuleId>te.gm</ModuleId>
  <ModuleId>te.srs</ModuleId>
  </RequiredModules>
  <Resources>
    <Resource name="SharedLibraryName" xlink:href="terralib_postgis"/>
    <Resource name="SQLDialectFile" xlink:href="postgis_dialect.xml"/>
    <Resource name="LangFile" xlink:href="pt.br"/>
    <Resource name="HelpFile" xlink:href="pgis.html"/>
  </Resources>
  <Parameters>
    <Parameter>
      <Name>DEFAULT_DATASET_CACHE_SIZE</Name>
      <Value>5000</Value>
    </Parameter>
    <Parameter>
      <Name>CLIENT_ENCODING</Name>
      <Value>LATIN1</Value>
    </Parameter>
    <Parameter>
      <Name>InitialPoolSize</Name>
      <Value>1</Value>
    </Parameter>
    <Parameter>
      <Name>MinPoolSize</Name>
      <Value>1</Value>
    </Parameter>
    <Parameter>
      <Name>MaxPoolSize</Name>
      <Value>1</Value>
    </Parameter>
  </Parameters>
</PluginInfo>

=== claudiobogossian/terralib5/resources/xml/mysql-plugin-info.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PluginInfo xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.terralib.org/schemas/plugin"
            xsd:schemaLocation="http://www.terralib.org/schemas/plugin ../../../../schemas/terralib/plugin/plugin_info.xsd"
            version="5.0.0-20110110"
            release="2011-01-01"
            engine="C++">
  <Name>te.da.mysql</Name>
  <DisplayName>MySQL Data Source Driver</DisplayName>
  <Description>This plugin enables TerraLib to access spatial data stored in a MySQL DBMS</Description>
  <TerraLibVersion>5.0.0-20100101</TerraLibVersion>
  <License xlink:href="http://www.gnu.org/licenses/lgpl-3.0-standalone.html">GNU Lesser General Public License v 3.0</License>
  <Category>Data Access</Category>
  <Site xlink:href="http://www.dpi.inpe.br/terralib5/wiki/doku.php?id=wiki:designimplementation:dataaccess:postgis"></Site>
  <Provider>
    <Name>Terralib Team</Name>
    <Site xlink:href="http://www.terralib.org/"></Site>
    <Email>terralib-team@terralib.org</Email>
  </Provider>
  <RequiredModules>
    <ModuleId>te.da</ModuleId>
  </RequiredModules>
  <Resources>
    <Resource name="SharedLibraryName" xlink:href="terralib_mysql"></Resource>
    <Resource name="QueryDialectFile" xlink:href="mysql_dialect.xml"></Resource>
  </Resources>
</PluginInfo>
